server:
  port: 8080
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/postgres
    locations:
      - classpath:db/migration
      - classpath:db/testdata
  r2dbc:
    username: root
    password: root
    url: r2dbc:postgresql://localhost:5432/postgres
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  application:
    name: loan-simulation
  lifecycle:
    timeout-per-shutdown-phase: 15s
url:
  parameter: http://localhost:3000/parameters

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"